basePath: /api
consumes:
- application/json
definitions:
  Credentials:
    properties:
      password:
        type: string
        x-go-name: Password
      username:
        type: string
        x-go-name: Username
    type: object
    x-go-package: github.com/babyplug/api-challenge-gin-gorm/dto
  CredentialsResponse:
    properties:
      prefix:
        type: string
        x-go-name: Prefix
      token:
        type: string
        x-go-name: Token
    type: object
    x-go-package: github.com/babyplug/api-challenge-gin-gorm/dto
host: some-url.com
info:
  description: Documentation of our Golang API.
  title: GolangAPIChallenge.
  version: 1.0.0
paths:
  /api/login:
    post:
      operationId: authenEndPoint
      parameters:
      - in: body
        name: Body
        schema:
          $ref: '#/definitions/Credentials'
      responses:
        "200":
          $ref: '#/responses/loginResponse'
      summary: Login route for authentication.
      tags:
      - Authentication
produces:
- application/json
responses:
  loginResponse:
    description: Response for login.
    schema:
      $ref: '#/definitions/CredentialsResponse'
schemes:
- http
securityDefinitions:
  bearer:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
